ignore:
    - "src/components/HomePostCard.jsx"
    - "src/components/Header.jsx"
    - "src/constants/icons.js"
    - "src/context"
    - "src/pages/Register.jsx"
    - "src/pages/Home.jsx"
    - "src/pages/Login.jsx"
    - "src/pages/Profile.jsx"
