ignore:
  - "src/Register.js"
  - "src/VerifyEmail.js"
  - "src/Profile.js"
  - "src/ResetPassword.js"
  - "src/Login.js"
  - "src/index.js"
  - "src/Home.js"
  - "src/pages/Profile.js"


 
